### ISSUE TITLE
remove scrolling from usersignup page and Remove analytics button from admin dashboard 

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#13]
Remove scrolling from usersignup.php, it's not needed

**Comment by parag1201** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

assigned

**Comment by prateek76** [comment]
@parag1201 any progress??

**Comment by Rattlecode17sh** [comment]
let me know if it is still open

**Comment by prateek76** [comment]
> let me know if it is still open

it's open you can go ahead

**Comment by Rattlecode17sh** [comment]
okay

**Comment by BLJS2warchief** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

#21 is open you can solve that
