### ISSUE TITLE
reduce the width of form in home page and fix the stretched logo

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#14]
Reduce the width of form in home page and fix the logo.

![fix2](https://user-images.githubusercontent.com/33982495/51076400-f82f7300-16bd-11e9-8b29-18e23f0ed6fc.png)

**Comment by Rattlecode17sh** [comment]
@claimboat claim

**Comment by Rattlecode17sh** [comment]
Can i slove this issue??

**Comment by prateek76** [comment]
@Rattlecode17sh yes you can

**Comment by Kartik2301** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
@Kartik2301 assigned to you

**Comment by Kartik2301** [comment]
prateek76 Sir could you please provide me some basic guide lines of how and where to begin

**Comment by Rattlecode17sh** [comment]
![screenshot 31](https://user-images.githubusercontent.com/38866385/51105005-c3323600-180d-11e9-90a1-41bcfcb25fb4.png)


Here is the screenshot of reduced width and screen size

**Comment by prateek76** [comment]
> prateek76 Sir could you please provide me some basic guide lines of how and where to begin

someone already made pr for this issue, you will be first assigned in next issue

also are you having problem in setting it up? tell me where are you stuck

**Comment by prateek76** [comment]
@Rattlecode17sh  please reduce more

**Comment by Rattlecode17sh** [comment]
okay

**Comment by Rattlecode17sh** [comment]
![screenshot 32](https://user-images.githubusercontent.com/38866385/51107151-fa0b4a80-1813-11e9-94a2-947da4a14b0c.png)

check this one

**Comment by prateek76** [comment]
@Rattlecode17sh for mobile view can you attach screenshots for that too

**Comment by Rattlecode17sh** [comment]
![screenshot 34](https://user-images.githubusercontent.com/38866385/51121182-cee92100-183c-11e9-92b9-454c40cc85d2.png)
