### ISSUE TITLE
Add username when user go to form.php

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#16]
Add username $_SESSION['user'] on right position of bar to show who is logged in

![screenshot from 2019-01-13 17-29-48](https://user-images.githubusercontent.com/33982495/51084982-ddf6a300-1758-11e9-9c6e-82dad6bf40e3.png)

**Comment by mohammed-adil** [comment]
@opencodebot claim

**Comment by mohammed-adil** [comment]
Hey @prateek76 Do you want to print email id of the user or the name of the user?
Because when i echo $_SESSION['user'], only email id is printed.

**Comment by prateek76** [comment]
> Hey @prateek76 Do you want to print email id of the user or the name of the user?
> Because when i echo $_SESSION['user'], only email id is printed.
> 
> Here's the output:
> 
> ![4](https://user-images.githubusercontent.com/31363829/51086933-8ebd6c00-1772-11e9-962a-1a9be20b9113.png)
> 
> I'll create a PR if this is the required output.

email will do :+1:
