### ISSUE TITLE
Remove background image from sidenav in student dashboard and implement new buttons(on sidenav) in student and admin dashboard page

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#22]
Remove background image from sidenav in student dashboard and implement new buttons(on sidenav) in student and admin dashboard page

The background image to be removed from sidenav-

![oc3](https://user-images.githubusercontent.com/33982495/51088236-1ad78f80-1783-11e9-81f3-6e9efcd19613.PNG)

The new buttons design -

![oc4](https://user-images.githubusercontent.com/33982495/51088242-2f1b8c80-1783-11e9-8dc1-e3e60897e9c2.PNG)

On hovering the buttons -

![oc5](https://user-images.githubusercontent.com/33982495/51088244-3478d700-1783-11e9-84f3-968bb360064b.PNG)

**Comment by Rattlecode17sh** [comment]
@opencode claim

**Comment by Rattlecode17sh** [comment]
Can you pleaese tell where these new buttons are to be placed

**Comment by Rattlecode17sh** [comment]
Can you pleaese tell me where these new buttons are to be placed

**Comment by prateek76** [comment]
> Can you pleaese tell me where these new buttons are to be placed

![screenshot from 2019-01-14 20-20-10](https://user-images.githubusercontent.com/33982495/51119889-f38fc980-1839-11e9-961c-0a529b99ff17.png)

these buttons similarly in admin dashboard

**Comment by parag1201** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
I will do it by tomorrow as i was working on some other issue
