### ISSUE TITLE
Make admin login page similar to students login page

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#25]
Fields required Username, email, password, branch ( ECE and IT ) keep this in selection dropdown,
filename - "adminLogin.php"

**Comment by mohammed-adil** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
@mohammed-adil assigned to you

**Comment by mohammed-adil** [comment]
Hey @prateek76 how am i supposed to verify admin login?
Don't i need to have admin credentials in DB, plus how does branch field work in admin login?
Can you give me a brief of how admin login page should work?

**Comment by prateek76** [comment]
> Hey @prateek76 how am i supposed to verify admin login?
> Don't i need to have admin credentials in DB, plus how does branch field work in admin login?
> Can you give me a brief of how admin login page should work?

you have to only make front end part for this issue
