### ISSUE TITLE
Make admin login logic 

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#27]
Make admin login logic "core/admin-login.php" and set session var as ece and it,also username, email should be added in session var on login.

**Comment by ShipraGaur** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
assigned to @ShipraGaur

**Comment by prateek76** [comment]
@ShipraGaur any progress??

**Comment by thesmallstar** [comment]
@prateek76 I will work on this :)

**Comment by thesmallstar** [comment]
@prateek76  I find two admin logics. One in the core and one in the root, why is it so? and on which on I need to work on?

**Comment by prateek76** [comment]
@thesmallstar which file in root?
