### ISSUE TITLE
suggest ideas which can be implemented in the project to make it better

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#29]
Selected suggestions will be awarded 20 points, don't make issues just comment it here

**Comment by thesmallstar** [comment]
1. The site is not responsive(not only home page  but also Applications page);
2. A calendar should be displayed to select dates( UX)
3. There is no need to ask for email. It will be rollno@iiita.ac.in(i guess)
4. The response after the signup is really weird. ( I would like to fix that) Using a Flash message.
5. Signup page has a very different page style. 
6. the feedback systems are mostly alert boxes which can be made better,
//I want to fix the above issues.:) 


I would like to work on the admin-pages(dashboard and other features of the website:), for now, I want to add the forgot password-login with verification of email. using local file. i.e a code will be generated in a local file which can be used to reset the password. The same feature can then be used to create a password reset link(later);

**Comment by prateek76** [comment]
forgot password is needed now, we will use LDAP integration for that, but all other suggestions looks good to me i will open issues for most of them.

**Comment by prateek76** [comment]
@thesmallstar can you explain what you want to say in 8th point

**Comment by thesmallstar** [comment]
Yes, 
![screenshot_6](https://user-images.githubusercontent.com/42006277/51288878-0b2aa600-1a24-11e9-9ec4-a1069c7981d6.png)

I think the link is not working correctly- it should open the specific image/upload related to that application instead- it directly opens the upload folder. 
![3](https://user-images.githubusercontent.com/42006277/51288937-3d3c0800-1a24-11e9-8ca7-819dab25dfc1.png)

secondly, since upload folder will contain all the upload we dont want some other user to see uploads other than his own, i.e we need to forbid direct access to the folder. ( Although this has to be done through ht access or later on server)

**Comment by thesmallstar** [comment]
Please check the above issue as well.
Also, i find that error checking on sign-up page is not correctly done. Even blank inputs are accepted , I would like to fix it, before u add flash messeging.

**Comment by thesmallstar** [comment]
@prateek76  in admin_login.php frontend validations can also be added , the admin can select the default "select Branch" and submit using it. I think We can disable the option for selection and only ece and IT option should be selected. I also want to add flash messaging to admin logic. I Consider them as different issues. Please check them :) 

![select](https://user-images.githubusercontent.com/42006277/51687508-a8836c80-2018-11e9-8844-0cda58509e3a.png)

**Comment by thesmallstar** [comment]
@prateek76  Please check the above issue I mentioned.  Also the alert boxes can be removed for the login page. Invalid credentials still comes as a alert.

**Comment by prateek76** [comment]
@thesmallstar you cannot login if you don't select the branch so what is the need of removing placeholder?

**Comment by thesmallstar** [comment]
@prateek76 yes, sorry I missed that.

**Comment by thesmallstar** [comment]
@prateek76 , I just noticed We can show "No uploads " instead of just blank box when there are no uploads in student dashboard and admin dashboard.

**Comment by prateek76** [comment]
> 1. The site is not responsive(not only home page  but also Applications page);
> 2. A calendar should be displayed to select dates( UX)
> 3. There is no need to ask for email. It will be [rollno@iiita.ac.in](mailto:rollno@iiita.ac.in)(i guess)
> 4. The response after the signup is really weird. ( I would like to fix that) Using a Flash message.
> 5. Signup page has a very different page style.
> 6. the feedback systems are mostly alert boxes which can be made better.
> 7. The titles of the web pages are not very correct.
> 8. The direct access to uploads folder should be forbidden(has to be added later),but the UP link int application details directly links to the uploads folder and not specific upload.
> 
> //I want to fix the above issues.:)
> 
> I would like to work on the admin-pages(dashboard and other features of the website:), for now, I want to add the forgot password-login with verification of email. using local file. i.e a code will be generated in a local file which can be used to reset the password. The same feature can then be used to create a password reset link(later);

3
