### ISSUE TITLE
Make home page responsive

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#31]
Home page (the login page is not responsive) make it responsive

**Comment by prateek76** [comment]
@supremenishant any progress ??

**Comment by crustyy** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

wait till tommorow after that you can solve this

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
Sorry i was busy with some other issues so will definitely do it by tomorrow

**Comment by Rattlecode17sh** [comment]
Can i get some time i was busy with some other issue
