### ISSUE TITLE
Remove analytics button from admin dashboard

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#39]
![lapis1](https://user-images.githubusercontent.com/33982495/51336136-d06b5100-1aa9-11e9-9a72-b6c57381e968.PNG)

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

assigned

**Comment by prateek76** [comment]
@Rattlecode17sh solve it in #13
