### ISSUE TITLE
fix button size in the modal

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#40]
![lapis2](https://user-images.githubusercontent.com/33982495/51336229-06a8d080-1aaa-11e9-98aa-ac977b683666.PNG)

accept, reject, pending and close button are going out of the form

**Comment by thesmallstar** [comment]
@prateek76  Can you tell me the specific browser you are using?  I couldn't find this issue as I checked in moz , chrome. & edge I am attaching the screenshots. 

Moz:
![screenshot_1](https://user-images.githubusercontent.com/42006277/51413841-346b4380-1b96-11e9-8440-830afd069b17.png)


edge: 
![3s](https://user-images.githubusercontent.com/42006277/51413873-55cc2f80-1b96-11e9-82be-8dd07828954e.png)

**Comment by prateek76** [comment]
@thesmallstar do a pull then try
