### ISSUE TITLE
reduce space b/w buttons in sidenav 

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#41]
Reduce space and also remove underline on hovering new application button in students_dashboard

**Comment by thesmallstar** [comment]
@opencodebot claim

**Comment by thesmallstar** [comment]
Sorry, I cannot work on more than two issues at once :) 
I am un-claiming the issues

**Comment by prateek76** [comment]
> @opencodebot claim

you can claim max two issue from each project, please solve other issues

**Comment by sharmamansi** [comment]
@ opencodebot claim

**Comment by sharmamansi** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

assigned

**Comment by thesmallstar** [comment]
@prateek76  Sorry I did not see the updated message that it is assigned to me. 
I will work on it.
