### ISSUE TITLE
Implement add more files option in students dashboard modal

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#54]
![assa](https://user-images.githubusercontent.com/33982495/51700493-4a18b700-2035-11e9-9169-533c64f0a62b.PNG)

so that student can upload images later

**Comment by thesmallstar** [comment]
I have made a PR for one of my issue, can I claim this ?

**Comment by vishnuk7** [comment]
@prateek76 Can I Work on this?

**Comment by prateek76** [comment]
@thesmallstar you have more issues assigned let @vishnuk7 work on this for now, after that you can do it

**Comment by prateek76** [comment]
@vishnuk7 go ahead

**Comment by thesmallstar** [comment]
@vishnuk7 all yours :)

**Comment by prateek76** [comment]
@vishnuk7 do you need any help?

**Comment by thesmallstar** [comment]
@prateek76  can I work on this?

**Comment by vishnuk7** [comment]
@prateek76  @thesmallstar I almost completed give me one more day
