### ISSUE TITLE
Remove yellow highlighting on auto complete for all input fields

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#60]
remove for all forms

![screenshot from 2019-01-28 12-49-02](https://user-images.githubusercontent.com/33982495/51820344-6e0d1e80-22fb-11e9-8821-cf3863dab061.png)

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

assigned to @Archies11

**Comment by Archies11** [comment]
@opencodebot unclaim
@prateek76 I can't work on this at present

**Comment by Archies11** [comment]
Does this repo come under the list of repos under opencodebot?

**Comment by anupm12** [comment]
@prateek76 I'll do this

**Comment by prateek76** [comment]
@Archies11  are you still working on this?

**Comment by Archies11** [comment]
![capture](https://user-images.githubusercontent.com/45824817/51895721-df6ad100-23d0-11e9-869c-ce3b69eb5a17.PNG)
The above is what I found when I tried to search for a possible solution online. Should I disable autocorrect in general?

**Comment by prateek76** [comment]
@Archies11 try this https://github.com/prateek76/hack36-wander/blob/master/css/login.css
