### ISSUE TITLE
outer border cuts the form at bottom increase its height

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#63]
![heighttt](https://user-images.githubusercontent.com/33982495/51822419-4077a380-2302-11e9-9989-8514b8a3f2cb.PNG)

**Comment by prateek76** [comment]
> @OpenCode claim

assigned to @vishnuk7

**Comment by prateek76** [comment]
@vishnuk7 same is the problem with admin login page, fix for that too

**Comment by vishnuk7** [comment]
@prateek76 ok

**Comment by prateek76** [comment]
@vishnuk7 do same for admin login, problem is there too and make a new pr
