### ISSUE TITLE
if address length is less than 30 remove "..." from the address in the tables

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#78]

**Comment by vishnuk7** [comment]
@prateek76  Can I work on this?

**Comment by prateek76** [comment]
@vishnuk7 solve #79 in this issue

**Comment by vishnuk7** [comment]
@prateek76 ok

**Comment by vishnuk7** [comment]
![image](https://user-images.githubusercontent.com/31013847/52167827-3fea6d00-2747-11e9-9a7f-aa841355c565.png)
![image](https://user-images.githubusercontent.com/31013847/52167830-44168a80-2747-11e9-96f3-9c78d1369aa1.png)

@prateek76 check this out
I fixed the problem,now it is working fine

**Comment by prateek76** [comment]
@vishnuk7 pr for this

**Comment by vishnuk7** [comment]
@prateek76 check my last commit 1e302fc, I already put all changes into that commit

**Comment by prateek76** [comment]
make pr for that @vishnuk7
