### ISSUE TITLE
when attaching more files add preview horizontally

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#85]

**Comment by thesmallstar** [comment]
I would like to work on this :)

**Comment by thesmallstar** [comment]
@vishnuk7 I made them appear verticle, I know how to make it horizontal, only if  you would allow me to do it or else it is all yours :)

**Comment by prateek76** [comment]
@vishnuk7 @thesmallstar how many issues you both have right now?

**Comment by vishnuk7** [comment]
@prateek76 2 issues

**Comment by prateek76** [comment]
@vishnuk7 issue number?

**Comment by prateek76** [comment]
@vishnuk7  #78  is partially solved please solve that first, also you can work on #62 
let @thesmallstar work on this

**Comment by prateek76** [comment]
@thesmallstar go ahead

**Comment by prateek76** [comment]
> @vishnuk7 I made them appear verticle, I know how to make it horizontal, only if you would allow me to do it or else it is all yours :)

you already have 3 issues @vishnuk7 you can work on this

**Comment by thesmallstar** [comment]
@prateek76 whom did you assign it to? 
I am Confused :P

**Comment by thesmallstar** [comment]
Btw, I am working only on 2 issues.

**Comment by prateek76** [comment]
@vishnuk7 you already have 3 issues @thesmallstar

**Comment by prateek76** [comment]
> Btw, I am working only on 2 issues.

issue number?

**Comment by thesmallstar** [comment]
83,61 
@prateek76 let Vishnu work on this.  I will take some other issue. No problem :)

**Comment by prateek76** [comment]
@vishnuk7 do you need any help?

**Comment by prateek76** [comment]
@vishnuk7 make new request for points your last request was for 30 points

**Comment by vishnuk7** [comment]
@prateek76 ok
