### ISSUE TITLE
make extension lowercase in application_submission script it is not matching the extension array if extension is in uppercase

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#89]
Fix for multiple file uploads

**Comment by thesmallstar** [comment]
@prateek76 I just tested it. Seems to be working fine.

**Comment by prateek76** [comment]
It's not appending file names to database only last file is being added

**Comment by thesmallstar** [comment]
Worked fine until I made the last pr, I think I messed something, I will fix it.

**Comment by thesmallstar** [comment]
I merged with master and Did a complete test here is what I got:
1. Upload folder before application: 
![ff2](https://user-images.githubusercontent.com/42006277/52175389-15d98f00-27c9-11e9-86ad-0d95324f0839.png)


2. Added files
![f1](https://user-images.githubusercontent.com/42006277/52175397-3ace0200-27c9-11e9-9819-54386b7bf4e2.png)


3. Upload folder after submission:
![ff3](https://user-images.githubusercontent.com/42006277/52175385-05c1af80-27c9-11e9-85f4-d77808d5c5bf.png)


4. Links in the dashboard: 
(the second last application)
![ff5](https://user-images.githubusercontent.com/42006277/52175398-415c7980-27c9-11e9-9148-734af3f33001.png)

Am I missing something?

**Comment by thesmallstar** [comment]
I merged with master and did the following test:
1. Uplload folder before form submission,
![ff2](https://user-images.githubusercontent.com/42006277/52175430-b62fb380-27c9-11e9-8055-f501ec5e8793.png)
2. Added files to form:
![fff1](https://user-images.githubusercontent.com/42006277/52175435-c778c000-27c9-11e9-8e81-d7067a80bce0.png)
3. UPload folder after submission:
![ff4](https://user-images.githubusercontent.com/42006277/52175439-dcedea00-27c9-11e9-9ce1-ac1f2900cf60.png)
4. The links in dashboard: 
![ffr5](https://user-images.githubusercontent.com/42006277/52175441-e7a87f00-27c9-11e9-9f13-7eb2e960c40e.png)



Am I missing anything? All the 1-2-3 links in dashboard also works correctly.

**Comment by prateek76** [comment]
@thesmallstar ok then problem may be on my side maybe xampp is not working properly 👍

**Comment by thesmallstar** [comment]
@prateek76  Yes, please test, I am also doing it I will comment if I find a bug. :)

**Comment by prateek76** [comment]
@thesmallstar i got the error the images i was uploading was having extension in uppercase , please make extension to lowercase as it was before

**Comment by thesmallstar** [comment]
Okay, I am doing it.

**Comment by thesmallstar** [comment]
You mean we need to accept both lowercase and upper case I.e png and PNG Both are acceptable, or anything else?

**Comment by prateek76** [comment]
also change redirection linkto "adminLogin.php" from "adminlogin" when admin logout in adminlogout.php locally it dont affect but on other servers it will show 404, it can be case sensitive , like on 000webhostapp deployment

**Comment by thesmallstar** [comment]
@prateek76 yes, it will be a issue on Linux servers. I will make the change
