### ISSUE TITLE
make filters work properly like if there is no pending applications on clicking pending application tab table should show no pending applications

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#93]
check here - https://iec2017029.000webhostapp.com/

**Comment by thesmallstar** [comment]
I have made a PR for two issues, Can i claim this?

**Comment by thesmallstar** [comment]
@prateek76  I am little confused what else comes under this issue?, I thought of No applications should be written if there are no applications in the dashboard, and 1-2 more in admin dashboard. Anything else you would suggest?

**Comment by prateek76** [comment]
@thesmallstar like if there are no pending applications but there are 2 accepted applications so if you are in all applications tab and click on pending applications tab all application are displayed now this is the problem you have to show no pending applications in the table

**Comment by thesmallstar** [comment]
@prateek76  ok :)

**Comment by thesmallstar** [comment]
I Checked all the sections, Here is what I saw:
I dont see a bug, am I missing something?
![m3](https://user-images.githubusercontent.com/42006277/52222322-47d21a80-28c9-11e9-93a9-19486a52ef69.png)
![m5](https://user-images.githubusercontent.com/42006277/52222323-486ab100-28c9-11e9-9e48-da671839c900.png)
![m1](https://user-images.githubusercontent.com/42006277/52222325-486ab100-28c9-11e9-8850-2d6e5f54c683.png)
![m2](https://user-images.githubusercontent.com/42006277/52222327-486ab100-28c9-11e9-979e-bfeecad79f81.png)

**Comment by prateek76** [comment]
check here https://iec2017029.000webhostapp.com/admin_dashboard.php
@thesmallstar 
click on new applications as there is no new application it should not display any row in the table instead no new application should be shown
