### ISSUE TITLE
add a loader (spinner) while table contents loads everytime

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Leave-Application-Portal#97]

**Comment by anupm12** [comment]
Can I work on this?

**Comment by anupm12** [comment]
@prateek76 Spinner should be added when the page is loading, right?

**Comment by anupm12** [comment]
ok @prateek76

**Comment by anupm12** [comment]
@prateek76  the spinner is working when the page loads but I'm unable to add it specifically to table.
Can you help me?

**Comment by prateek76** [comment]
@anupm12 you can add spinner to the table when the page initially loads and remove it after ajax call in success part

**Comment by anupm12** [comment]
ok will try now.

**Comment by vishnuk7** [comment]
@prateek76 Can I work on this?

**Comment by prateek76** [comment]
@vishnuk7 go ahead
